#backend appspec.yml

version: 0.0
os: linux
files:
        - source: /
          destination: /home/ubuntu/QOS/build

permissions:
- object: /home/ubuntu/QOS/build
  pattern: "**"
  owner: ubuntu
  group: ubuntu
  mode: 755
hooks:
 AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
