# This is a basic workflow to help you get started with Actions

name: gradle CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, gjdms611-patch-1 ]
  pull_request:
    branches: [ master, gjdms611-patch-1 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
        
      - name: Grant execute permission for gradlew
        run: chmod +x ./backend/gradlew
        shell: bash
      
      - name: Build with Gradle
        working-directory: ./backend
        run: ./gradlew build
        shell: bash
                
      - name: Make zip file(backend)
        working-directory: ./backend/build/libs
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: Deploy to s3
        run: |
          aws s3 rm \
            --recursive \
            --region ap-northeast-2 \
            s3://q-tect-order-system/backend/
          aws s3 cp \
            --region ap-northeast-2 \
            ./backend/build/libs/$GITHUB_SHA.zip s3://q-tect-order-system/backend/

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
            --application-name qos-deploy \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name develop \
            --region ap-northeast-2 \
            --s3-location bucket=q-tect-order-system,bundleType=zip,key=backend/$GITHUB_SHA.zip
